### ISSUE TITLE
My exersices Praktika 1 -7 denb proverte plz

### ISSUE THREAD

**Issue by ghost** [kotsolesya/OPtaAM_practice_PS3_2017#11]
[Praktika opam Gorelik PS 3-1 1-7 denb.zip](https://github.com/kotsolesya/OPtaAM_practice_PS3_2017/files/1474571/Praktika.opam.Gorelik.PS.3-1.1-7.denb.zip)

**Comment by kotsolesya** [comment]
архів перевіряти не буду. Скидай код і ссилочки на нього в github

**Comment by ghost** [comment]
PerezaliL

**Comment by kotsolesya** [comment]
де ссилка?
