### ISSUE TITLE
Andrienko

### ISSUE THREAD

**Issue by Attiny2000** [kotsolesya/OPtaAM_practice_PS3_2017#20]
https://github.com/Attiny2000/Practice/tree/master/Day%E2%84%965

**Comment by kotsolesya** [comment]
як мені зрозуміти які номера задачок зроблено?

**Comment by kotsolesya** [comment]
не дублюй Issues, якщо вже є один то в нього і додавай коменти, поки не закрию

**Comment by Attiny2000** [comment]
https://github.com/Attiny2000/Practice/tree/master/Day%E2%84%966
6 и 7 дни

**Comment by Attiny2000** [comment]
https://github.com/Attiny2000/Practice/tree/master/Day%E2%84%968
8 день

**Comment by kotsolesya** [comment]
за 8 день почитай, уважно!, завдання на першій сторінці
