### ISSUE TITLE
Butsenko chec oll day

### ISSUE THREAD

**Issue by Nazar173** [kotsolesya/OPtaAM_practice_PS3_2017#23]
https://github.com/Nazar173/Praktika-OPtAM

**Comment by kotsolesya** [comment]
Задача 428(1.2.3) 3 день - то що ти шукаєш - мінімум чи максимум і навіщо тобі 
`# define M_PI           3.14159265358979323846`

**Comment by kotsolesya** [comment]
day4/6.cpp
/Naiiti priklad figyri ABCD po zadanim ctoronam
//ÀÂ, ÀÑ i DC
Якщо ти шукаєш приклад фігури то навіщо функція знаходження гіпотенузи?
 calculate_the_hypotenuse(double x, double y)
ти сам зрозумів що тобі треба знайти?

**Comment by kotsolesya** [comment]
За 6-7 день двы задачі з однакомими умовами!!!!!
БУДЬ УВАЖНИМ!
/* Naiti ploshy figuri ABCD po zadanim storonam AB,AC,DC.*/
/* Naiti ploshy figuri ABCD po zadanim storonam AB,AC,DC.*/
