### ISSUE TITLE
Guds day 5,6,7 full task

### ISSUE THREAD

**Issue by VitalikGuds** [kotsolesya/OPtaAM_practice_PS3_2017#27]
https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam.git

**Comment by kotsolesya** [comment]
хочу бачити все структуровано по каталогам і без .exe файлів

**Comment by VitalikGuds** [comment]
day 5 https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam/commit/17c7ff0fc7a98951d216ce8f1af0ab306bce4a01

**Comment by VitalikGuds** [comment]
day 6-7 https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam/tree/master/%D0%B4%D0%B5%D0%BD%D1%8C%206-7

**Comment by kotsolesya** [comment]
роби сам!

**Comment by VitalikGuds** [comment]
https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam/tree/master/day%209 day 9 
task 4.	Ввести з консолі ціле число. Порахувати кількість одиниць в його бінарному представленні ("1011" -> 3).

**Comment by VitalikGuds** [comment]
https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam/tree/master/day%208 day 8 
task 17 Організувати базу даних для довідково-бібліографічного відділу бібліотеки, що містить таку інформацію: автор книги; назва книги; кількість зареєстрованих примірників.

**Comment by kotsolesya** [comment]
task 17 ?? за 8 день в тебе 20 і 35

**Comment by VitalikGuds** [comment]
то 20
я перепутал

**Comment by VitalikGuds** [comment]
не то написал

**Comment by VitalikGuds** [comment]
https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam/tree/master/%D0%B4%D0%B5%D0%BD%D1%8C%209 задание 11
11.	Ввести цілі числа n та i, вивести ціле число, у якого i -й біт відрізняється від i -го біта числа n, а всі інші біти збігаються з бітами числа n на тих же позиціях. Наприклад, якщо введені 5 і 1, відповіддю буде 7

**Comment by VitalikGuds** [comment]
https://github.com/VitalikGuds/Practic-PS-3-1-OPPtam/tree/master/day%205 переделал задание 5 день
