### ISSUE TITLE
shved:day1[q 1-5]

### ISSUE THREAD

**Issue by dsnnnnnnnnn** [kotsolesya/OPtaAM_practice_PS3_2017#4]
Собстно, вот работа за 1й день, тут первые 4 на ++ а остальные 1 на питоне (да, я смогу сказать, что я там написал)
https://github.com/nexusloh/practical

**Comment by kotsolesya** [comment]
1 день зараховано (у 5.py не зрозуміло який номер задачі)
2 день підпиши номера задач, які зробив
