### ISSUE TITLE
Guds dey 1, 1-5

### ISSUE THREAD

**Issue by VitalikGuds** [kotsolesya/OPtaAM_practice_PS3_2017#5]
https://github.com/VitalikGuds/Practic-PS-3-1.git 

this is a 1 day job, please check

**Comment by kotsolesya** [comment]
Задачі по днях кидай відповідно по каталогах, для зручності.  
розшифруй що написано - //äàíà ñòðîêà ïîäñ÷èòàòü êîëè÷åñòâî áóêâ â ïîñëåäíåì åå ñëîâå 
**dey 1 рядки задание 5.cpp** це яка задача?

2 день
```
template<size_t N> 
::std::ostream& operator<< (::std::ostream& ss, const int (&ar)[N] )
```
впевнений, що пояниш це?

**Comment by VitalikGuds** [comment]
template<size_t N>  // шаблон <>-описания шаблона 
::std::ostream& operator<< (::std::ostream& ss, const int (&ar)[N] ) // перезагрузка оператора
